[package]
name = "torii-fetcher-jsonrpc"
version = "0.1.0"
edition = "2021"
description = "JSON-RPC fetcher implementation for Torii runtime"
authors = ["Torii Runtime <dev@torii.rs>"]
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
tokio.workspace = true
tracing.workspace = true
torii-core = { path = "../../core/torii-core" }
url.workspace = true
