[package]
name = "torii-sink-log"
version = "0.1.0"
edition = "2021"
description = "Logging sink for Torii runtime"
authors = ["Torii Runtime <dev@torii.rs>"]
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
torii-core = { path = "../../core/torii-core" }
tracing.workspace = true
