#!/usr/bin/env bash
set -euo pipefail

current_file="perf/synthetic-runs/metrics.tsv"
baselines_dir="perf/synthetic-baselines"

if [ ! -f "$current_file" ]; then
  echo "Current metrics not found at $current_file" >&2
  exit 1
fi

# Find latest baseline
latest_baseline=$(ls -1t "$baselines_dir" 2>/dev/null | head -1)
baseline_file=""
if [ -n "$latest_baseline" ]; then
  baseline_file="$baselines_dir/$latest_baseline/metrics.tsv"
fi

echo "# 📊 Synthetic Benchmark Results"
echo ""

if [ -f "$baseline_file" ]; then
  echo "Comparing against baseline: **$latest_baseline**"
  echo ""
else
  echo "**No previous baseline found. This is the first run.**"
  echo ""
fi

echo "## Performance Summary"
echo ""
echo "| Token Type | Duration (ms) | Blocks | Transactions | Events | Envelopes | Blocks/sec | Events/sec |"
echo "|------------|---------------|--------|---------------|--------|-----------|------------|------------|"

while IFS=$'\t' read -r token_type duration blocks txs events envelopes blocks_sec tx_sec events_sec envs_sec extract_ms decode_ms sink_ms commit_ms; do
  printf "| %s | %s | %s | %s | %s | %s | %.2f | %.2f |\n" \
    "$token_type" "$duration" "$blocks" "$txs" "$events" "$envelopes" "$blocks_sec" "$events_sec"
done < <(tail -n +2 "$current_file")

echo ""

# If we have a baseline, show comparison
if [ -f "$baseline_file" ]; then
  echo "## Comparison with Baseline"
  echo ""
  echo "| Token Type | Metric | Baseline | Current | Change |"
  echo "|------------|--------|----------|---------|--------|"
  
  while IFS=$'\t' read -r token_type duration blocks txs events envelopes blocks_sec tx_sec events_sec envs_sec extract_ms decode_ms sink_ms commit_ms; do
    # Get baseline values
    baseline_duration=$(grep "^${token_type}" "$baseline_file" | cut -f2)
    baseline_events_sec=$(grep "^${token_type}" "$baseline_file" | cut -f9)
    baseline_extract=$(grep "^${token_type}" "$baseline_file" | cut -f11)
    baseline_decode=$(grep "^${token_type}" "$baseline_file" | cut -f12)
    baseline_sink=$(grep "^${token_type}" "$baseline_file" | cut -f13)
    
    if [ -n "$baseline_events_sec" ] && [ -n "$events_sec" ]; then
      change=$(awk "BEGIN {printf \"%.1f\", (($events_sec - $baseline_events_sec) / $baseline_events_sec) * 100}")
      emoji=""
      if (( $(awk "BEGIN {print ($change > 5)}") )); then
        emoji="📈"
      elif (( $(awk "BEGIN {print ($change < -5)}") )); then
        emoji="📉"
      else
        emoji="➡️"
      fi
      printf "| %s | Throughput (events/sec) | %.2f | %.2f | %s %.1f%% |\n" \
        "$token_type" "$baseline_events_sec" "$events_sec" "$emoji" "$change"
    fi
    
    if [ -n "$baseline_duration" ] && [ -n "$duration" ]; then
      change=$(awk "BEGIN {printf \"%.1f\", (($duration - $baseline_duration) / $baseline_duration) * 100}")
      emoji=""
      if (( $(awk "BEGIN {print ($change > 5)}") )); then
        emoji="⚠️"
      elif (( $(awk "BEGIN {print ($change < -5)}") )); then
        emoji="✅"
      else
        emoji="➡️"
      fi
      printf "| %s | Duration (ms) | %s | %s | %s %.1f%% |\n" \
        "$token_type" "$baseline_duration" "$duration" "$emoji" "$change"
    fi
  done < <(tail -n +2 "$current_file")
  
  echo ""
  echo "**Legend:**"
  echo "- ✅ Improvement (faster)"
  echo "- ⚠️ Regression (slower)"
  echo "- 📈 Throughput increase"
  echo "- 📉 Throughput decrease"
  echo "- ➡️ No significant change (<5%)"
fi

echo ""
echo "## Stage Latency Breakdown"
echo ""
echo "| Token Type | Extract (ms) | Decode (ms) | Sink (ms) | Commit (ms) |"
echo "|------------|--------------|--------------|-----------|-------------|"

while IFS=$'\t' read -r token_type duration blocks txs events envelopes blocks_sec tx_sec events_sec envs_sec extract_ms decode_ms sink_ms commit_ms; do
  printf "| %s | %s | %s | %s | %s |\n" \
    "$token_type" "$extract_ms" "$decode_ms" "$sink_ms" "$commit_ms"
done < <(tail -n +2 "$current_file")

echo ""
echo "---"
echo "*Generated by Synthetic Benchmark CI*"
