[package]
name = "torii-sink-postgresql"
version = "0.1.0"
edition = "2021"
description = "PostgreSQL sink implementation for Torii runtime"
authors = ["Torii Runtime <dev@torii.rs>"]
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
introspect-types.workspace = true
introspect-value.workspace = true
starknet-types-core.workspace = true
primitive-types = "0.14"

# Local crates
torii-core = { path = "../../core/torii-core" }
torii-types-introspect = { path = "../../types/torii-types-introspect" }
torii-types-erc20 = { path = "../../types/torii-types-erc20" }
torii-types-erc721 = { path = "../../types/torii-types-erc721" }
