[package]
name = "torii-types-introspect"
version = "0.1.0"
edition = "2021"
description = "Introspect protocol event types for Torii"
authors = ["Torii Runtime <dev@torii.rs>"]
license = "Apache-2.0"

[dependencies]
serde.workspace = true
torii-core = { path = "../../core/torii-core" }
introspect-value.workspace = true
introspect-events.workspace = true
introspect-types.workspace = true
starknet-types-core.workspace = true
starknet.workspace = true
