[package]
name = "torii-decoder-introspect"
version = "0.1.0"
edition = "2021"
description = "Introspect decoder for Torii runtime"
authors = ["Torii Runtime <dev@torii.rs>"]
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
torii-core = { path = "../../core/torii-core" }
torii-types-introspect = { path = "../../types/torii-types-introspect" }
tracing.workspace = true
dojo-introspect-events.workspace = true
dojo-introspect-types.workspace = true
dojo-introspect-utils.workspace = true
dojo-types-manager.workspace = true
introspect-types.workspace = true
introspect-events.workspace = true
introspect-value.workspace = true
starknet-types-core.workspace = true
